### PR TITLE
Added Github Actions

### LINKED ISSUE #16: Add Github Actions
I've never used Github Actions before, but it would be a nice addition to be able to build, test and check coverage.

See: https://github.com/BamPeers/rust-ci-github-actions-workflow

### PR DESCRIPTION
**Pull request by daladim**
Closes #16 

This is using the basic Rust action automatically suggested by GitHub.
The stock https://github.com/BamPeers/rust-ci-github-actions-workflow you suggested seems to run on Ubuntu. I'm not sure forking and customizing it is worth it.

I think we'll always be able to add clippy, rustfmt, etc. later from this first step

### CODE REVIEW

**Comment by daladim** [comment]
Hmm, I did not read https://github.com/BamPeers/rust-ci-github-actions-workflow thoroughly, there are many good ideas there that are easy to use after all.

I'll push new commits

**Comment by daladim** [comment]
Well, I cannot fix all Clippy errors without bumping to a new major version.

Thus, I am not (yet) adding a Clippy job in this MR.
I think using advanced test with code coverage is out of my reach for this MR.

So, I'm not sure how completely this MR closes #18 , I'll let you decide whether you'll want to keep this issue open after this MR

**Comment by roblabla** [comment]
I hightly suggest using the actions from https://github.com/actions-rs. They run on all runners (including windows), are well maintained, and provide a lot of niceties, such as proper parsing of rust's output to annotate the diff views with warning/errors, or downloading a known version of the rust compiler.

A minimal version of this would be replacing the cargo build and cargo test jobs with

```yaml
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
```

**Comment by daladim** [comment]
Thanks for the suggestion @roblabla , I've added jobs from `actions-rs`

**Review by n4r1b — APPROVED** [review]
Very nice! Thanks @daladim

**Pull request merged**
